### ISSUE TITLE
Could you please share more details about the data used in your experiments?

### ISSUE THREAD

**Issue by fkhmaissia** [satish1901/In-situ-Water-quality-monitoring-in-Oil-and-Gas-operations#4]
Hello, thank you for the great work! 
I am trying to reproduce your results. Could you please point me towards the exact format of the dataset that you used? It would be really helpful if you could share the metadata or any code excerpt.  I am using landsatxplore.api as follow.

`
from landsatxplore.api import API
api = API(,)
scenes = api.search(
    dataset='landsat_ot_c2_l2',
    latitude=??,
    longitude=??,
    start_date=??,
    end_date=??,
    max_cloud_cover=50
)
`

Thanks!

**Comment by satish1901** [comment]
Hello 
sorry for the late response!
I downloaded the data from here 
https://earthexplorer.usgs.gov/
I hope this helps. Please let me know if there is any other confusion 

The latitude and longitude i can't share because those were the propriety information of a company, I used location of their ponds and the corresponding measurements done by the ground team. 

Thank you

**Comment by satish1901** [comment]
Hello,

I am closing this issue if there is no further queries.

Thank you
